name = "kes_im"
type = "webpack"
workers_dev = false
account_id = "f6eb193c5ada002251ec96253583e74d"
zone_id = "5b5fa1156dac645ae9a36479bf982e10"
routes = [
  "kes.im/*",
  "api.kes.im/*"
]

[[kv_namespaces]]
binding = "kesim_data"
id = "767fc2258dd94aa09ddcacdac19b1e23"
preview_id=""

[site]
bucket = "./public"