name = "kes_im"
type = "webpack"
workers_dev = false
account_id = "f6eb193c5ada002251ec96253583e74d"
zone_id = "5b5fa1156dac645ae9a36479bf982e10"
routes = [
  "beta.kes.im/*",
  "api.kes.im/*"
]

[[kv_namespaces]]
binding = "kesim_data"
id = "b5b51fce86a74b4eba5a11e7d9e06d16"
preview_id="b5b51fce86a74b4eba5a11e7d9e06d16"

[site]
bucket = "./public"